In [1]:
import json
import pandas as pd

# Part 1: Reading and investigating data

Open up the `player_data.json` and investigate the data structure.

In [ ]:
with open('player_data.json') as json_file:
    data = json.load(json_file)
data

In [19]:
data[0].keys()

dict_keys(['PERSON_ID', 'FIRST_NAME', 'LAST_NAME', 'DISPLAY_FIRST_LAST', 'DISPLAY_LAST_COMMA_FIRST', 'DISPLAY_FI_LAST', 'BIRTHDATE', 'SCHOOL', 'COUNTRY', 'LAST_AFFILIATION', 'HEIGHT', 'WEIGHT', 'SEASON_EXP', 'JERSEY', 'POSITION', 'ROSTERSTATUS', 'TEAM_ID', 'TEAM_NAME', 'TEAM_ABBREVIATION', 'TEAM_CODE', 'TEAM_CITY', 'PLAYERCODE', 'FROM_YEAR', 'TO_YEAR', 'DLEAGUE_FLAG', 'NBA_FLAG', 'GAMES_PLAYED_FLAG', 'DRAFT_YEAR', 'DRAFT_ROUND', 'DRAFT_NUMBER', 'CAREER_STATS', 'GAMELOG'])

In [32]:
data[0]['GAMELOG'][0].keys()

dict_keys(['SEASON_ID', 'Player_ID', 'Game_ID', 'GAME_DATE', 'MATCHUP', 'WL', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'PLUS_MINUS', 'VIDEO_AVAILABLE', 'TEAM_ABBREVIATION', 'TEAM_ID'])

# Part 2:  Creating the Dataframe

Create a data frame where each row corresponds to a game for each player. You must have atleast the following columns in your final dataframe:

'DISPLAY_FIRST_LAST', 'PERSON_ID', 'TEAM_ID', 'AST', 'BLK', 'DREB','Game_ID',  'MIN', 'PTS', 'REB', 'TEAM_ABBREVIATION'

*You can include additional columns in your dataframe, so you don't have to do additional work to remove other columns.*

In [24]:


df = pd.DataFrame()
for person in data:
    if len(person['GAMELOG']) == 0:
        continue
    #only takes data from those dict keys as columns, no need to drop unnecessary
    df1 = pd.DataFrame(person, columns=['DISPLAY_FIRST_LAST', 'PERSON_ID', 'TEAM_ID'], index=[0])
    df2 = pd.DataFrame(person['GAMELOG'])
    merged = pd.merge(df1, df2, left_on='PERSON_ID', right_on='Player_ID', how='outer')
    df = pd.concat([df, merged])
    
#each merge would end up repeated the index from each merge table, 
#because Pd does not require unique indeces, so drop, and then reset to inplace
df.reset_index(drop=True, inplace=True)

,DISPLAY_FIRST_LAST,PERSON_ID,TEAM_ID_x,AST,BLK,DREB,FG3A,FG3M,FG3_PCT,FGA,...,PTS,Player_ID,REB,SEASON_ID,STL,TEAM_ABBREVIATION,TEAM_ID_y,TOV,VIDEO_AVAILABLE,WL
0,Alex Abrines,203518,0,0,0,0,1,0,0.000,2,...,0,203518,0,22018,0,OKC,1610612760,0,1,W
1,Alex Abrines,203518,0,0,0,1,2,1,0.500,2,...,3,203518,1,22018,0,OKC,1610612760,0,1,W
2,Alex Abrines,203518,0,0,2,1,5,1,0.200,6,...,7,203518,1,22018,0,OKC,1610612760,0,1,L
3,Alex Abrines,203518,0,0,0,1,4,2,0.500,4,...,6,203518,1,22018,0,OKC,1610612760,0,1,W
4,Alex Abrines,203518,0,1,0,1,7,3,0.429,7,...,9,203518,1,22018,0,OKC,1610612760,0,1,W
5,Alex Abrines,203518,0,0,0,1,3,2,0.667,4,...,8,203518,3,22018,1,OKC,1610612760,0,1,W
6,Alex Abrines,203518,0,0,0,4,2,0,0.000,4,...,6,203518,4,22018,0,OKC,1610612760,0,1,W
7,Alex Abrines,203518,0,0,0,0,1,0,0.000,1,...,0,203518,0,22018,0,OKC,1610612760,1,1,L
8,Alex Abrines,203518,0,2,0,1,5,1,0.200,6,...,5,203518,1,22018,1,OKC,1610612760,0,1,L
9,Alex Abrines,203518,0,0,0,3,1,0,0.000,2,...,0,203518,3,22018,1,OKC,1610612760,2,1,W
10,Alex Abrines,203518,0,1,0,3,4,1,0.250,4,...,3,203518,3,22018,0,OKC,1610612760,1,1,L
11,Alex Abrines,203518,0,1,0,1,2,0,0.000,2,...,0,203518,1,22018,3,OKC,1610612760,1,1,W
12,Alex Abrines,203518,0,1,0,1,2,0,0.000,3,...,2,203518,1,22018,0,OKC,1610612760,1,1,W
13,Alex Abrines,203518,0,1,0,2,11,7,0.636,11,...,21,203518,2,22018,0,OKC,1610612760,0,1,W
14,Alex Abrines,203518,0,1,0,2,8,1,0.125,9,...,3,203518,3,22018,0,OKC,1610612760,0,1,W
15,Alex Abrines,203518,0,1,0,1,2,0,0.000,2,...,0,203518,1,22018,0,OKC,1610612760,0,1,L
16,Alex Abrines,203518,0,0,0,0,1,0,0.000,1,...,0,203518,0,22018,0,OKC,1610612760,0,1,W
17,Alex Abrines,203518,0,0,0,0,1,0,0.000,2,...,0,203518,0,22018,0,OKC,1610612760,1,1,W
18,Alex Abrines,203518,0,2,1,2,6,2,0.333,6,...,8,203518,2,22018,2,OKC,1610612760,1,1,W
19,Alex Abrines,203518,0,0,0,2,4,2,0.500,6,...,6,203518,2,22018,0,OKC,1610612760,1,1,L
20,Alex Abrines,203518,0,0,0,3,3,0,0.000,3,...,0,203518,4,22018,1,OKC,1610612760,1,1,W
21,Alex Abrines,203518,0,0,0,0,10,3,0.300,12,...,9,203518,0,22018,1,OKC,1610612760,0,1,W
22,Alex Abrines,203518,0,3,0,4,2,1,0.500,4,...,7,203518,4,22018,0,OKC,1610612760,1,1,W
23,Alex Abrines,203518,0,2,2,1,7,2,0.286,8,...,8,203518,1,22018,0,OKC,1610612760,0,1,W
24,Alex Abrines,203518,0,0,0,2,10,5,0.500,15,...,25,203518,2,22018,0,OKC,1610612760,0,1,W
25,Alex Abrines,203518,0,0,1,0,1,1,1.000,2,...,3,203518,0,22018,4,OKC,1610612760,1,1,W
26,Alex Abrines,203518,0,0,0,1,3,0,0.000,5,...,2,203518,1,22018,2,OKC,1610612760,0,1,W
27,Alex Abrines,203518,0,1,0,1,5,2,0.400,5,...,6,203518,1,22018,0,OKC,1610612760,0,1,L
28,Alex Abrines,203518,0,2,0,1,1,0,0.000,1,...,0,203518,1,22018,0,OKC,1610612760,0,1,L
29,Alex Abrines,203518,0,1,0,1,7,2,0.286,10,...,10,203518,2,22018,1,OKC,1610612760,2,1,L
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26071,Ivica Zubac,1627826,1610612746,3,0,0,0,0,0.000,5,...,7,1627826,2,22018,0,LAL,1610612747,2,1,L
26072,Ivica Zubac,1627826,1610612746,0,4,11,0,0,0.000,16,...,24,1627826,16,22018,0,LAL,1610612747,2,1,W
26073,Ivica Zubac,1627826,1610612746,1,0,4,0,0,0.000,12,...,10,1627826,8,22018,0,LAL,1610612747,4,1,L
26074,Ivica Zubac,1627826,1610612746,0,1,4,0,0,0.000,8,...,18,1627826,4,22018,0,LAL,1610612747,2,1,L
26075,Ivica Zubac,1627826,1610612746,1,1,5,0,0,0.000,6,...,17,1627826,7,22018,0,LAL,1610612747,0,1,L
26076,Ivica Zubac,1627826,1610612746,1,0,6,0,0,0.000,14,...,26,1627826,12,22018,0,LAL,1610612747,4,1,W
26077,Ivica Zubac,1627826,1610612746,1,0,3,0,0,0.000,2,...,7,1627826,3,22018,0,LAL,1610612747,0,1,W
26078,Ivica Zubac,1627826,1610612746,0,2,2,0,0,0.000,3,...,5,1627826,2,22018,0,LAL,1610612747,0,1,L
26079,Ivica Zubac,1627826,1610612746,1,1,3,0,0,0.000,10,...,10,1627826,5,22018,0,LAL,1610612747,0,1,L
26080,Ivica Zubac,1627826,1610612746,1,0,6,0,0,0.000,8,...,11,1627826,9,22018,1,LAL,1610612747,0,1,W
26081,Ivica Zubac,1627826,1610612746,0,0,1,0,0,0.000,2,...,4,1627826,2,22018,0,LAL,1610612747,1,1,W
26082,Ivica Zubac,1627826,1610612746,0,0,6,0,0,0.000,6,...,9,1627826,8,22018,0,LAL,1610612747,2,1,L
26083,Ivica Zubac,1627826,1610612746,2,1,4,0,0,0.000,6,...,10,1627826,6,22018,0,LAL,1610612747,1,1,L
26084,Ivica Zubac,1627826,1610612746,1,1,1,0,0,0.000,4,...,8,1627826,2,22018,0,LAL,1610612747,1,1,L
26085,Ivica Zubac,1627826,1610612746,3,1,0,0,0,0.000,8,...,7,1627826,2,22018,0,LAL,1610612747,2,1,L
26086,Ivica Zubac,1627826,1610612746,0,1,3,0,0,0.000,8,...,6,1627826,5,22018,0,LAL,1610612747,1,1,L
26087,Ivica Zubac,1627826,1610612746,2,2,8,0,0,0.000,10,...,18,1627826,11,22018,0,LAL,1610612747,1,1,W
26088,Ivica Zubac,1627826,1610612746,1,4,3,0,0,0.000,12,...,19,1627826,4,22018,0,LAL,1610612747,1,1,L
26089,Ivica Zubac,1627826,1610612746,0,2,9,0,0,0.000,10,...,16,1627826,11,22018,2,LAL,1610612747,1,1,W
26090,Ivica Zubac,1627826,1610612746,1,1,0,0,0,0.000,1,...,0,1627826,0,22018,0,LAL,1610612747,0,1,L
26091,Ivica Zubac,1627826,1610612746,1,0,2,0,0,0.000,2,...,4,1627826,2,22018,0,LAL,1610612747,0,1,L
26092,Ivica Zubac,1627826,1610612746,0,0,1,0,0,0.000,4,...,6,1627826,1,22018,0,LAL,1610612747,0,1,W
26093,Ivica Zubac,1627826,1610612746,0,1,2,0,0,0.000,0,...,0,1627826,2,22018,0,LAL,1610612747,0,1,W
26094,Ivica Zubac,1627826,1610612746,0,0,1,0,0,0.000,0,...,0,1627826,1,22018,0,LAL,1610612747,0,1,W
26095,Ivica Zubac,1627826,1610612746,0,1,1,0,0,0.000,2,...,0,1627826,2,22018,0,LAL,1610612747,1,1,L
26096,Ivica Zubac,1627826,1610612746,0,0,1,0,0,0.000,2,...,0,1627826,2,22018,0,LAL,1610612747,0,1,W
26097,Ivica Zubac,1627826,1610612746,1,0,4,0,0,0.000,3,...,5,1627826,6,22018,0,LAL,1610612747,1,1,L
26098,Ivica Zubac,1627826,1610612746,0,0,4,0,0,0.000,5,...,9,1627826,8,22018,1,LAL,1610612747,2,1,W
26099,Ivica Zubac,1627826,1610612746,1,0,1,0,0,0.000,1,...,0,1627826,2,22018,0,LAL,1610612747,0,1,W
26100,Ivica Zubac,1627826,1610612746,0,1,0,0,0,0.000,1,...,0,1627826,1,22018,0,LAL,1610612747,0,1,L

In [25]:
df

,DISPLAY_FIRST_LAST,PERSON_ID,TEAM_ID_x,AST,BLK,DREB,FG3A,FG3M,FG3_PCT,FGA,...,PTS,Player_ID,REB,SEASON_ID,STL,TEAM_ABBREVIATION,TEAM_ID_y,TOV,VIDEO_AVAILABLE,WL
0,Alex Abrines,203518,0,0,0,0,1,0,0.000,2,...,0,203518,0,22018,0,OKC,1610612760,0,1,W
1,Alex Abrines,203518,0,0,0,1,2,1,0.500,2,...,3,203518,1,22018,0,OKC,1610612760,0,1,W
2,Alex Abrines,203518,0,0,2,1,5,1,0.200,6,...,7,203518,1,22018,0,OKC,1610612760,0,1,L
3,Alex Abrines,203518,0,0,0,1,4,2,0.500,4,...,6,203518,1,22018,0,OKC,1610612760,0,1,W
4,Alex Abrines,203518,0,1,0,1,7,3,0.429,7,...,9,203518,1,22018,0,OKC,1610612760,0,1,W
5,Alex Abrines,203518,0,0,0,1,3,2,0.667,4,...,8,203518,3,22018,1,OKC,1610612760,0,1,W
6,Alex Abrines,203518,0,0,0,4,2,0,0.000,4,...,6,203518,4,22018,0,OKC,1610612760,0,1,W
7,Alex Abrines,203518,0,0,0,0,1,0,0.000,1,...,0,203518,0,22018,0,OKC,1610612760,1,1,L
8,Alex Abrines,203518,0,2,0,1,5,1,0.200,6,...,5,203518,1,22018,1,OKC,1610612760,0,1,L
9,Alex Abrines,203518,0,0,0,3,1,0,0.000,2,...,0,203518,3,22018,1,OKC,1610612760,2,1,W
10,Alex Abrines,203518,0,1,0,3,4,1,0.250,4,...,3,203518,3,22018,0,OKC,1610612760,1,1,L
11,Alex Abrines,203518,0,1,0,1,2,0,0.000,2,...,0,203518,1,22018,3,OKC,1610612760,1,1,W
12,Alex Abrines,203518,0,1,0,1,2,0,0.000,3,...,2,203518,1,22018,0,OKC,1610612760,1,1,W
13,Alex Abrines,203518,0,1,0,2,11,7,0.636,11,...,21,203518,2,22018,0,OKC,1610612760,0,1,W
14,Alex Abrines,203518,0,1,0,2,8,1,0.125,9,...,3,203518,3,22018,0,OKC,1610612760,0,1,W
15,Alex Abrines,203518,0,1,0,1,2,0,0.000,2,...,0,203518,1,22018,0,OKC,1610612760,0,1,L
16,Alex Abrines,203518,0,0,0,0,1,0,0.000,1,...,0,203518,0,22018,0,OKC,1610612760,0,1,W
17,Alex Abrines,203518,0,0,0,0,1,0,0.000,2,...,0,203518,0,22018,0,OKC,1610612760,1,1,W
18,Alex Abrines,203518,0,2,1,2,6,2,0.333,6,...,8,203518,2,22018,2,OKC,1610612760,1,1,W
19,Alex Abrines,203518,0,0,0,2,4,2,0.500,6,...,6,203518,2,22018,0,OKC,1610612760,1,1,L
20,Alex Abrines,203518,0,0,0,3,3,0,0.000,3,...,0,203518,4,22018,1,OKC,1610612760,1,1,W
21,Alex Abrines,203518,0,0,0,0,10,3,0.300,12,...,9,203518,0,22018,1,OKC,1610612760,0,1,W
22,Alex Abrines,203518,0,3,0,4,2,1,0.500,4,...,7,203518,4,22018,0,OKC,1610612760,1,1,W
23,Alex Abrines,203518,0,2,2,1,7,2,0.286,8,...,8,203518,1,22018,0,OKC,1610612760,0,1,W
24,Alex Abrines,203518,0,0,0,2,10,5,0.500,15,...,25,203518,2,22018,0,OKC,1610612760,0,1,W
25,Alex Abrines,203518,0,0,1,0,1,1,1.000,2,...,3,203518,0,22018,4,OKC,1610612760,1,1,W
26,Alex Abrines,203518,0,0,0,1,3,0,0.000,5,...,2,203518,1,22018,2,OKC,1610612760,0,1,W
27,Alex Abrines,203518,0,1,0,1,5,2,0.400,5,...,6,203518,1,22018,0,OKC,1610612760,0,1,L
28,Alex Abrines,203518,0,2,0,1,1,0,0.000,1,...,0,203518,1,22018,0,OKC,1610612760,0,1,L
29,Alex Abrines,203518,0,1,0,1,7,2,0.286,10,...,10,203518,2,22018,1,OKC,1610612760,2,1,L
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26071,Ivica Zubac,1627826,1610612746,3,0,0,0,0,0.000,5,...,7,1627826,2,22018,0,LAL,1610612747,2,1,L
26072,Ivica Zubac,1627826,1610612746,0,4,11,0,0,0.000,16,...,24,1627826,16,22018,0,LAL,1610612747,2,1,W
26073,Ivica Zubac,1627826,1610612746,1,0,4,0,0,0.000,12,...,10,1627826,8,22018,0,LAL,1610612747,4,1,L
26074,Ivica Zubac,1627826,1610612746,0,1,4,0,0,0.000,8,...,18,1627826,4,22018,0,LAL,1610612747,2,1,L
26075,Ivica Zubac,1627826,1610612746,1,1,5,0,0,0.000,6,...,17,1627826,7,22018,0,LAL,1610612747,0,1,L
26076,Ivica Zubac,1627826,1610612746,1,0,6,0,0,0.000,14,...,26,1627826,12,22018,0,LAL,1610612747,4,1,W
26077,Ivica Zubac,1627826,1610612746,1,0,3,0,0,0.000,2,...,7,1627826,3,22018,0,LAL,1610612747,0,1,W
26078,Ivica Zubac,1627826,1610612746,0,2,2,0,0,0.000,3,...,5,1627826,2,22018,0,LAL,1610612747,0,1,L
26079,Ivica Zubac,1627826,1610612746,1,1,3,0,0,0.000,10,...,10,1627826,5,22018,0,LAL,1610612747,0,1,L
26080,Ivica Zubac,1627826,1610612746,1,0,6,0,0,0.000,8,...,11,1627826,9,22018,1,LAL,1610612747,0,1,W
26081,Ivica Zubac,1627826,1610612746,0,0,1,0,0,0.000,2,...,4,1627826,2,22018,0,LAL,1610612747,1,1,W
26082,Ivica Zubac,1627826,1610612746,0,0,6,0,0,0.000,6,...,9,1627826,8,22018,0,LAL,1610612747,2,1,L
26083,Ivica Zubac,1627826,1610612746,2,1,4,0,0,0.000,6,...,10,1627826,6,22018,0,LAL,1610612747,1,1,L
26084,Ivica Zubac,1627826,1610612746,1,1,1,0,0,0.000,4,...,8,1627826,2,22018,0,LAL,1610612747,1,1,L
26085,Ivica Zubac,1627826,1610612746,3,1,0,0,0,0.000,8,...,7,1627826,2,22018,0,LAL,1610612747,2,1,L
26086,Ivica Zubac,1627826,1610612746,0,1,3,0,0,0.000,8,...,6,1627826,5,22018,0,LAL,1610612747,1,1,L
26087,Ivica Zubac,1627826,1610612746,2,2,8,0,0,0.000,10,...,18,1627826,11,22018,0,LAL,1610612747,1,1,W
26088,Ivica Zubac,1627826,1610612746,1,4,3,0,0,0.000,12,...,19,1627826,4,22018,0,LAL,1610612747,1,1,L
26089,Ivica Zubac,1627826,1610612746,0,2,9,0,0,0.000,10,...,16,1627826,11,22018,2,LAL,1610612747,1,1,W
26090,Ivica Zubac,1627826,1610612746,1,1,0,0,0,0.000,1,...,0,1627826,0,22018,0,LAL,1610612747,0,1,L
26091,Ivica Zubac,1627826,1610612746,1,0,2,0,0,0.000,2,...,4,1627826,2,22018,0,LAL,1610612747,0,1,L
26092,Ivica Zubac,1627826,1610612746,0,0,1,0,0,0.000,4,...,6,1627826,1,22018,0,LAL,1610612747,0,1,W
26093,Ivica Zubac,1627826,1610612746,0,1,2,0,0,0.000,0,...,0,1627826,2,22018,0,LAL,1610612747,0,1,W
26094,Ivica Zubac,1627826,1610612746,0,0,1,0,0,0.000,0,...,0,1627826,1,22018,0,LAL,1610612747,0,1,W
26095,Ivica Zubac,1627826,1610612746,0,1,1,0,0,0.000,2,...,0,1627826,2,22018,0,LAL,1610612747,1,1,L
26096,Ivica Zubac,1627826,1610612746,0,0,1,0,0,0.000,2,...,0,1627826,2,22018,0,LAL,1610612747,0,1,W
26097,Ivica Zubac,1627826,1610612746,1,0,4,0,0,0.000,3,...,5,1627826,6,22018,0,LAL,1610612747,1,1,L
26098,Ivica Zubac,1627826,1610612746,0,0,4,0,0,0.000,5,...,9,1627826,8,22018,1,LAL,1610612747,2,1,W
26099,Ivica Zubac,1627826,1610612746,1,0,1,0,0,0.000,1,...,0,1627826,2,22018,0,LAL,1610612747,0,1,W
26100,Ivica Zubac,1627826,1610612746,0,1,0,0,0,0.000,1,...,0,1627826,1,22018,0,LAL,1610612747,0,1,L

# Part 3: Pandas Questions

Answer the following questions

## 1 
- Find the player who scored the most points in an individual game last season.

-  Now do the same for rebounds, blocks, and assists.

In [254]:
def group_players(df):
    return df.groupby(['DISPLAY_FIRST_LAST'])

def most_for_game_attribute(df, attribute):
    max_score = df[attribute].max()
    game_stats = df.loc[df[attribute] == max_score]
    return game_stats['DISPLAY_FIRST_LAST']

In [61]:
most_for_game_attribute(df, 'REB')
most_for_game_attribute(df, 'PTS')

23773    Karl-Anthony Towns
Name: DISPLAY_FIRST_LAST, dtype: object

In [350]:



most_for_game_attribute(df, 'REB')
most_for_game_attribute(df, 'BLK')
most_for_game_attribute(df, 'AST')
most_for_game_attribute(df, 'PTS')

10323    James Harden
10348    James Harden
Name: DISPLAY_FIRST_LAST, dtype: object

## 2: 

- Find the player who scored the most points for the entire season.

- Now do the same for rebounds, blocks, and assists.

In [359]:
def most_for_season_attribute(df, attribute):
    grouped_players = group_players(df)
    sum_by_person = grouped_players[attribute].sum()
    max_sum = sum_by_person.nlargest(1)
    return max_sum

In [360]:

test = most_for_season_attribute(df, 'REB')
test

DISPLAY_FIRST_LAST
Andre Drummond    1232
Name: REB, dtype: int64

In [379]:
player_grouped = group_players(df)
player = player_grouped['AST'].sum().idmax()

AttributeError: 'Series' object has no attribute 'idmax'

## 3:
How many players played in at least 82 games last season?

In [262]:
def at_least_82(df):
    #initialize list of players
    players_over_82 = []
    grouped_players = group_players(df)
    for player in grouped_players:
        player_name = player[0]
        num_of_games = len(player[1])
        if num_of_games >= 82:
            players_over_82.append(player_name)
    return players_over_82

In [361]:
len(at_least_82(df))

21

In [384]:
(df['DISPLAY_FIRST_LAST'].value_counts()>=82).sum()

21

## 4: 
- Find which team scored the most points for the entire season.

- Now do the same for rebounds, blocks, and assists.

In [260]:
def team_with_most_attribute(df, attribute):
    grouped_teams = df.groupby('TEAM_ABBREVIATION')
    sum_of_attr = grouped_teams[attribute].sum()
    max_sum = sum_of_attr.nlargest(1)
    return max_sum

In [261]:
team_with_most_attribute(df, 'PTS')

TEAM_ABBREVIATION
MIL    9686
Name: PTS, dtype: int64

## 5:
Which team had the most players play for them last season?

In [270]:

def team_most_played_players(df):
    grouped_teams = df.groupby('TEAM_ABBREVIATION')
    unique_players = grouped_teams['DISPLAY_FIRST_LAST'].nunique()
    max_played = unique_players.nlargest(1)
    return max_played

In [364]:
team = team_most_played_players(df)
pd.DataFrame(team)

                   DISPLAY_FIRST_LAST
TEAM_ABBREVIATION
MEM                                28

## 6:
- Did any players play for more than one team last year?

- What is the most number of teams a player played for last season?

In [272]:
def play_for_most_teams(df):
    players_grouped = group_players(df)
    ## get the unique team abbr for each players, count if more than 1
    teams_played_for = players_grouped["TEAM_ABBREVIATION"].nunique()
    most_teamed_player = teams_played_for.nlargest(1)
    return most_teamed_player

In [273]:
play_for_most_teams(df)

DISPLAY_FIRST_LAST
Alec Burks    3
Name: TEAM_ABBREVIATION, dtype: int64

## 7:

Find the player who scored the least amount of points while playing in at least 40 games last season.

In [329]:
def filter_40_plus_games(df):
    players_grouped = group_players(df)
    filtered_players_40 = players_grouped.filter(lambda x: len(x) > 40)
    return filtered_players_40

def least_points_with_40_games(df):
    filtered_players = filter_40_plus_games(df)
    sum_points = filtered_players.groupby("DISPLAY_FIRST_LAST")['PTS'].sum()
    least_scorer = sum_points.nsmallest(1)
    return least_scorer

In [330]:
least_points_with_40_games(df)

DISPLAY_FIRST_LAST
Sindarius Thornwell    62
Name: PTS, dtype: int64

# Part 4: Pandas and Probability

## 8: 

What is the probability that a random player had a game where they scored more than 40 points?

In [321]:
#retrieve total number of unique players
def total_players(df):
    grouped_players = group_players(df)
    return len(grouped_players)

#calculate odds of getting num1 in sample space num2
def calculate_odds(num1, num2):
    return (num1/num2)

In [393]:
len(df[df['PTS']>40])/len(df)

0.004214397915788667

## 9:

What is the probability that a randomly selected player from last season would average more than 20 points per game?

In [398]:
import statistics

#return a DF of all the games featuring players who have scored over x amount
def attribute_over_x(df, attribute, x):
    grouped_players = group_players(df)
    #filter by selecting where mean of attribute is greater than amount
    over_x_avg = grouped_players.filter(lambda y : statistics.mean(y[attribute]) > x)
    return over_x_avg

def num_of_20_ppg(df):
    #get data_frame of all games with players who have 20 or better average
    players_over_20 = attribute_over_x(df, 'PTS', 20)
    grouped_players = group_players(players_over_20)
    #regroup and get the length to get count
    return len(grouped_players)


#probability of getting a player with 20 plus ppg average at random
def probs_of_20_avg(df):
    players_total = total_players(df)
    over_20_ppg_players = num_of_20_ppg(df)
    return calculate_odds(over_20_ppg_players, players_total)

In [399]:
probs_of_20_avg(df)

0.062264150943396226

In [395]:
import numpy as np
np.sum(player_grouped['PTS'].mean()>20)

33

# Advanced Questions

## 10: 
Find the player who scored the least amount of points while playing in at least 40 games and averageing at least 15 minutes per game last season.

In [389]:
def filter_15_min_per_game(df):
    players_grouped = group_players(df)
    players_15_min_pg = players_grouped.filter(lambda x : statistics.mean(x['MIN']) > 15)
    return players_15_min_pg

def least_points_with_40_games_15_min(df):
    #first filter for players who have played 40 games
    filtered_players_40_games = filter_40_plus_games(df)
    #then filter for players who averaged at least 15 min per game
    filtered_players_15_mins = attribute_over_x(filtered_players_40_games, 'MIN', 15)
    #then get player with worst sum
    sum_points = filtered_players_15_mins.groupby("DISPLAY_FIRST_LAST")['PTS'].sum()
    least_scorer = sum_points.nsmallest(1)
    return least_scorer

In [390]:
least_points_with_40_games_15_min(df)

DISPLAY_FIRST_LAST
Tyson Chandler    173
Name: PTS, dtype: int64

## 11: 
Which player scored the largest share of points for their team throughout the season.

In [373]:
#get a series object with each team and their cumulative score for the season
def team_by_score(df):
    grouped_teams = df.groupby(["TEAM_ABBREVIATION"])
    score_per_team = grouped_teams['PTS'].sum()
    return score_per_team
    
def best_team_player(df):
    team_scores = team_by_score(df)
    grouped_players = group_players(df)  
    attr_over_40 = grouped_players.map(lambda x : x['PTS']/team_scores[x["TEAM_ABBREVIATION"]])

In [375]:
team_by_score(df)
best_team_player(df)

AttributeError: 'DataFrameGroupBy' object has no attribute 'map'

## 12:

What is the probability that a randomly selected player had at least one game in which they scored 40 points last season.

In [365]:

def scored_40_plus(df, attribute):
    grouped_players = group_players(df)
    #filter by selecting where max of the attribute is over 40
    attr_over_40 = grouped_players.filter(lambda x : x[attribute].max() > 40)
    return attr_over_40

def num_of_40_plus(df):
    players_over_40_pts = scored_40_plus(df, 'PTS')
    grouped_over_40 = group_players(players_over_40_pts)
    num_over_40 = len(grouped_over_40)
    return num_over_40

def odds_of_40_pt_game(df):
    total = total_players(df)
    num_40_pt_players = num_of_40_plus(df)
    return calculate_odds(num_40_pt_players, total)

In [366]:
odds_of_40_pt_game(df)

0.05849056603773585

## 13: 

A double-double is when a player records for any of the two follow categories: points, rebounds, assists, steals, or blocks. 
What is the probability that a randomly selected player had a double-double in a game last season?

In [ ]:
#your code here

## 14:

What is the probability that a randomnly selected game had a player record a triple-double in that game?

In [ ]:
#your code here

# Part 5: Super Duper Challenge

## 15:

How many players last season averaged more points per game than their career average?